name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag virtual-gloomhaven-board:${GITHUB_REF#refs/tags/v*}
